name: Test
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build: [Release]
        arch: [x86, x64]
        cxx: [g++, clang++, ClangCl, v143]
        feature: [
          [AVX, 32, '-mavx', '/arch:AVX'],
          [AVX2, 32, '-mavx2', '/arch:AVX2'],
        ]
        exclude:
          - os: ubuntu-22.04
            cxx: v143
          - os: ubuntu-22.04
            cxx: ClangCl
          - os: windows-latest
            cxx: g++
          - os: windows-latest
            cxx: clang++

        include:
          - os: ubuntu-22.04
            arch: x86
            cmake_args: "-DCMAKE_CXX_FLAGS=-m32"
          - os: ubuntu-22.04
            arch: x64
            cmake_args: "-DCMAKE_CXX_FLAGS=-m64"
          - os: windows-latest
            arch: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-latest
            arch: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"

    name: "${{matrix.os}}-${{matrix.cxx}}-${{matrix.build}}-${{matrix.arch}}-${{matrix.feature[0]}}"
    runs-on: ${{matrix.os}}
    steps:
      - name: Dispatch Trigger
        if: ${{ startsWith(github.event.action, 'Dependency') }}
        run: >
          echo "Triggered by dependency: ${{github.event.client_payload.cause}}"

      - name: Clone
        uses: actions/checkout@v3

      - if: matrix.os == 'ubuntu-22.04' && matrix.arch == 'x86'
        name: Prepare Linux for cross-compilation
        run: |
          sudo apt update
          sudo apt install g++-multilib

      - if: matrix.os == 'ubuntu-22.04'
        name: Configure (Linux)
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
          -S .
          -B out
          ${{matrix.cmake_args}}
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DCMAKE_CXX_FLAGS="${{matrix.feature[2]}} -Wall -Wextra"

      - if: matrix.os == 'windows-latest'
        name: Configure (Windows)
        run: >
          cmake
          -S .
          -B out
          ${{matrix.cmake_args}} -T "${{matrix.cxx}}"
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DCMAKE_CXX_FLAGS="${{matrix.feature[3]}} /utf-8 /W3 /bigobj /EHsc"

      - name: Build
        run: cmake --build out --config ${{matrix.build}}

      - name: Test
        run: cd out && ctest -V -C ${{matrix.build}}